<a href="https://colab.research.google.com/github/koustav0502/Intro-to-ml-dl/blob/main/Copy_of_Assignment_2KP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy 

In [3]:
import numpy as np 


In [ ]:
# create a matrix 3x3 with values ranging from 50,58
#dont write code in this block
#ideal output is 


array([[50, 51, 52],
       [53, 54, 55],
       [56, 57, 58]])

In [6]:
#write code here
import numpy as np
num=50
x=np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    x[i,j]=num
    num=num+1

print(x)


#or
#a = np.arange(50,59).reshape(3,3)


[[50. 51. 52.]
 [53. 54. 55.]
 [56. 57. 58.]]


In [4]:
# try recreating following array; If need some hint pm :)
#dont run this cell

In [5]:
#write your code here . 
import numpy as np
num=0.25
k=np.zeros((4,10))
num=0.25
for i in range(0,4):
  for j in range(0,10):
    k[i,j]=num
    num=num+0.25

k
#or
#k=np.zeros((4,10))
#for i in range(0,4):
#  for j in range(0,10):
#    k[i,j]=num
#    num=num+0.25
#print(k)


array([[ 0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,
         2.5 ],
       [ 2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,
         5.  ],
       [ 5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
         7.5 ],
       [ 7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
        10.  ]])

suppose you store above array into a variable named `mat`, 
and you are asked to perform slicing operations to get sub parts of the `mat` 

In [ ]:
# using slicing operation return this array
#dont write your code here

array([[3.5 , 3.75, 4.  ],
       [6.  , 6.25, 6.5 ]])

In [ ]:
#write code here

In [7]:
mat=k
mat[1:3,3:6]


array([[3.5 , 3.75, 4.  ],
       [6.  , 6.25, 6.5 ]])

In [ ]:
#use different numpy operations on `mat` to get following output
#dont write code in this block



array([[0.75, 3.25, 5.75, 8.25],
       [1.  , 3.5 , 6.  , 8.5 ],
       [1.25, 3.75, 6.25, 8.75],
       [1.5 , 4.  , 6.5 , 9.  ],
       [1.75, 4.25, 6.75, 9.25]])

In [8]:
mat[:,2:7].T



array([[0.75, 3.25, 5.75, 8.25],
       [1.  , 3.5 , 6.  , 8.5 ],
       [1.25, 3.75, 6.25, 8.75],
       [1.5 , 4.  , 6.5 , 9.  ],
       [1.75, 4.25, 6.75, 9.25]])

In [ ]:
#use different numpy operations on `mat` to get following output
#dont write code in this block



array([0.75, 3.25, 5.75, 8.25])

In [9]:
#write your code here. 

mat[0:4,2:3].flatten()


array([0.75, 3.25, 5.75, 8.25])

In [ ]:
#use different numpy operations on `mat` to get following output
#dont write code in this block
#note that there is difference between above question and this question, In above question shape of the output array is (4,) and in this block, shape of output is (1,4)


array([[0.75, 3.25, 5.75, 8.25]])

In [10]:
z=mat[0:4,2:3].T
print(z.shape)
z


(1, 4)


array([[0.75, 3.25, 5.75, 8.25]])

In [12]:
#whats the sum of all elements in `mat`, 
sum_all = np.sum(mat)
sum_row = np.sum(mat, axis=1)
sum_column = np.sum(mat, axis=0)
print("sum of all elements in `mat` :", sum_all)
print("sum across rows in `mat` :", sum_row)
print("sum across columns in `mat` :", sum_column)

sum of all elements in `mat` : 205.0
sum across rows in `mat` : [13.75 38.75 63.75 88.75]
sum across columns in `mat` : [16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]


In [ ]:
# whats the standard deviation of all values in mat? 
std_mat = np.std(mat)
print("std of mat is : ", std_mat)

std of mat is :  2.885849095153799


In [15]:
!wget https://raw.githubusercontent.com/abhi-glitchhg/Intro-to-ml-dl/main/Week2/Assignment%202/data.csv

--2022-05-28 14:52:36--  https://raw.githubusercontent.com/abhi-glitchhg/Intro-to-ml-dl/main/Week2/Assignment%202/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2243759 (2.1M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   2.14M  --.-KB/s    in 0.06s   

2022-05-28 14:52:36 (33.4 MB/s) - ‘data.csv’ saved [2243759/2243759]



#pandas

In [13]:
import pandas as pd

In [16]:
dataframe = pd.read_csv("data.csv")

In [ ]:
dataframe

InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1        536365     71053                  WHITE METAL LANTERN         6   
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...         ...       ...                                  ...       ...   
25010    538351     22149           FELTCRAFT 6 FLOWER FRIENDS        23   
25011    538351     22150             3 STRIPEY MICE FELTCRAFT         1   
25012    538351     22174                           PHOTO CUBE         4   
25013    538351     22326  ROUND SNACK BOXES SET OF4 WOODLAND          1   
25014    538351     22327    ROUND SNACK BOXES SET OF 4 SKULLS         2   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
25010  12/10/2010 15:17       5.06         NaN  United Kingdom  
25011  12/10/2010 15:17       5.06         NaN  United Kingdom  
25012  12/10/2010 15:17       4.21         NaN  United Kingdom  
25013  12/10/2010 15:17       6.77         NaN  United Kingdom  
25014  12/10/2010 15:17       6.77         NaN         United   

[25015 rows x 8 columns]

In [ ]:
# check if there are any null values; print columnwise number of null values, and its percentage

In [22]:
dataframe.isnull().sum()

907000

In [ ]:
# how would you handle this null data points? - write in short..


In [ ]:
#write here.



In [ ]:
# print list of all different countries and number of times it appeared in `Country` column  ; Also plot a count plot for `Country` column.


United Kingdom     23709
Germany              309
France               287
EIRE                 228
Norway               147
Portugal              94
Spain                 45
Lithuania             35
Iceland               31
Italy                 25
Australia             22
Denmark               20
Channel Islands       17
Japan                 17
Belgium               12
Poland                 8
Switzerland            6
Netherlands            2
United                 1
Name: Country, dtype: int64

In [ ]:
#write code here for plotting.


In [ ]:
#dataframe where country value correspond to "United Kingdom" 
#dont run this cell
british_dataframe 

InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER       6.0   
1        536365     71053                  WHITE METAL LANTERN       6.0   
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER       8.0   
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE       6.0   
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.       6.0   
...         ...       ...                                  ...       ...   
12456    537381     22865               HAND WARMER OWL DESIGN      10.0   
12457    537381     22632            HAND WARMER RED RETROSPOT      24.0   
12458    537381     22633               HAND WARMER UNION JACK      20.0   
12459    537381     22867              HAND WARMER BIRD DESIGN      24.0   
12460    537381     22601       CHRISTMAS RETROSPOT ANGEL WOOD      17.0   

           InvoiceDate  UnitPrice  CustomerID         Country  
0       12/1/2010 8:26       2.55     17850.0  United Kingdom  
1       12/1/2010 8:26       3.39     17850.0  United Kingdom  
2       12/1/2010 8:26       2.75     17850.0  United Kingdom  
3       12/1/2010 8:26       3.39     17850.0  United Kingdom  
4       12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                ...        ...         ...             ...  
12456  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12457  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12458  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12459  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12460  12/6/2010 13:13       0.85     14667.0  United Kingdom  

[11806 rows x 8 columns]

In [ ]:
# now as every entry in "country" column of british_dataframe is same ("United Kingdom"); we can just remove the column 
#as it is not providing much information to us

In [ ]:
#drop country column of `british_dataframe`

In [ ]:
#Now make dataframe containing countries other than UK, name the dataframe as non_british_dataframe

In [ ]:
#remove the row which has null entry in `Country` Column; 
#dont remove the rows which have null values in column other than `Country`


In [ ]:
#write code here. 

In [ ]:

#now we want you to sort the dataframe acccording to the "UnitPrice" column; sorting should be descending
#if there is a tie/ same value use quantity as tie-braker. 


In [ ]:
# find the mean, maximum and minimum  of unit price based on country ; hint - use `groupby` operation
